name: Build and Deploy Jupyter-Book

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Jupyter Book
    runs-on: ubuntu-latest
    steps:
      # Set up the execution environment
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialise conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
      - name: Setup conda environments from lock files
        shell: bash -el {0}
        run: |
          conda create --name bookbuilder --file bookbuilder/conda-linux-64.lock
          conda create --name igrf --file binder/lockfiles/conda-linux-64.lock
          conda run --no-capture-output -n igrf python -m ipykernel install --user --name igrf
      # Execute notebooks and build book
      - name: Execute notebooks against igrf python kernel
        shell: bash -el {0}
        run: |
          conda run -n bookbuilder \
            pytest --numprocesses auto --nbmake --overwrite --nbmake-kernel=igrf notebooks/*.ipynb
      - name: Build jupyter book
        if: success() || failure()
        shell: bash -el {0}
        run: conda run -n bookbuilder jupyter-book build .
      - name: Upload artifact to pass to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html
      - name: Upload artifact to pass to Netlify
        if: ${{ github.event.pull_request && (success() || failure()) }}
        uses: actions/upload-artifact@v4
        with:
          name: html-preview
          path: _build/html
  deploy-main:
    name: Deploy main branch to GitHub Pages
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  deploy-preview:
    name: Deploy PR preview to Netlify
    needs: build
    if: ${{ github.event.pull_request && (success() || failure()) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-preview
          path: _build/html
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: _build/html
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
